# Generated by Django 2.2.2 on 2019-09-04 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190904_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school.SchoolModel'),
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.StudentModel'),
        ),
    ]
