# Generated by Django 2.2.2 on 2019-09-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190905_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='school.CityModel'),
        ),
    ]
