# Generated by Django 2.1.3 on 2019-09-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190905_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolmodel',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
